//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomOperations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandomOperations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMITH          1.006  1.006      1
        ///JOHNSON        0.810  1.816      2
        ///WILLIAMS       0.699  2.515      3
        ///JONES          0.621  3.136      4
        ///BROWN          0.621  3.757      5
        ///DAVIS          0.480  4.237      6
        ///MILLER         0.424  4.660      7
        ///WILSON         0.339  5.000      8
        ///MOORE          0.312  5.312      9
        ///TAYLOR         0.311  5.623     10
        ///ANDERSON       0.311  5.934     11
        ///THOMAS         0.311  6.245     12
        ///JACKSON        0.310  6.554     13
        ///WHITE          0.279  6.834     14
        ///HARRIS   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dist_all_last {
            get {
                return ResourceManager.GetString("dist_all_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARY           2.629  2.629      1
        ///PATRICIA       1.073  3.702      2
        ///LINDA          1.035  4.736      3
        ///BARBARA        0.980  5.716      4
        ///ELIZABETH      0.937  6.653      5
        ///JENNIFER       0.932  7.586      6
        ///MARIA          0.828  8.414      7
        ///SUSAN          0.794  9.209      8
        ///MARGARET       0.768  9.976      9
        ///DOROTHY        0.727 10.703     10
        ///LISA           0.704 11.407     11
        ///NANCY          0.669 12.075     12
        ///KAREN          0.667 12.742     13
        ///BETTY          0.666 13.408     14
        ///HELEN    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dist_female_first {
            get {
                return ResourceManager.GetString("dist_female_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAMES          3.318  3.318      1
        ///JOHN           3.271  6.589      2
        ///ROBERT         3.143  9.732      3
        ///MICHAEL        2.629 12.361      4
        ///WILLIAM        2.451 14.812      5
        ///DAVID          2.363 17.176      6
        ///RICHARD        1.703 18.878      7
        ///CHARLES        1.523 20.401      8
        ///JOSEPH         1.404 21.805      9
        ///THOMAS         1.380 23.185     10
        ///CHRISTOPHER    1.035 24.220     11
        ///DANIEL         0.974 25.194     12
        ///PAUL           0.948 26.142     13
        ///MARK           0.938 27.081     14
        ///DONALD   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dist_male_first {
            get {
                return ResourceManager.GetString("dist_male_first", resourceCulture);
            }
        }
    }
}
